services:
  api:
    build:
      .
    ports:
      - "8080:8080"
    environment:
      CONN_STR="user= dbname=restful_readlist host=localhost port=5432 sslmode=disable"

    depends_on:
      - db
  db:
    image: postgres